version: '3'


services:

  #前端网关nginx-gateay
  nginx-gateway:
#    image: nginx:1.21.5
    image: registry.cn-hangzhou.aliyuncs.com/u_ta_other/nginx:1.21.5
    container_name: go-zero-nginx
    #restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8888:8081
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/log:/var/log/nginx
    networks:
      - go-zero-net


networks:
  go-zero-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/16

